apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: terraform-init
spec:
  workspaces:
    - name: source
  params:
    - name: stack
      type: string
  steps:
    - name: init
      image: hashicorp/terraform:1.7.5
      workingDir: $(workspaces.source.path)/$(params.stack)
      script: |
        terraform version
        terraform init -backend-config=backend.hcl
